// Route definitions
export const ROUTES = {
  HOME: '/',
  PRIVACY: '/privacy',
  TERMS: '/terms',
  COOKIES: '/cookies',
  REFUND: '/refund',
  SECURITY: '/security',
  STARTER_FORM: '/starter-form',
  GROWTH_FORM: '/growth-form',
  SCALE_FORM: '/scale-form',
  IMPRINT: '/imprint',
  BLOG: '/blog',
  BLOG_POST: '/blog/:slug',
  CASE_STUDIES: '/case-studies',
  CASE_STUDY_DETAIL: '/case-studies/:slug',
  SIGNUP: '/signup',
  SIGNIN: '/signin',
  PAYMENT: '/payment',
  DASHBOARD: '/dashboard',
  SETUP: '/setup',
  SETUP_FORM: '/setup-form/:packageName',
  SETUP_PAYMENT: '/setup-payment/:packageName',
  SETUP_STATUS: '/setup-status/:packageName',
  SETUP_DASHBOARD: '/setup-dashboard',
  ADMIN_DASHBOARD: '/admin',
} as const;
